name: FortUTF Linux

on: [push]

jobs:
  build: 
    name: Ubuntu Latest Tests
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Build Tests
        run: |
            cmake -H. -Bbuild -DBUILD_TESTS=ON
            cmake --build build
      - name: Run Tests
        run: |
             ./build/FortUTF_Tests
             if [ $? -eq 0 ]; then
                echo "Unit Tests completed succesfully"
                exit 0
             else
                echo "Unit Tests failed"
                exit 1
             fi
                

  build_example:
    name: Ubuntu Latest Example
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Build Example Project
        run: |
             cd examples/demo_project
             cmake -H. -Bbuild
             cmake --build build
             ./build/DEMO_PROJ_Tests
             if [ $? -eq 0 ]; then
                echo "Unit Tests completed succesfully"
                exit 0
             else
                echo "Unit Tests failed"
                exit 1
             fi

  code_coverage:
    name: Code Coverage
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@master
      - name: Get Coverage Data
        run: |
            sudo apt install -y lcov
            lcov --gcov-tool $(which gcov) --directory . --capture --output-file temp.info -b src/
            lcov --remove temp.info 'tests/*' 'tests/test_assertions/*' -o FortUTF.info
      - uses: codecov/codecov-action@v1
        with:
          file: FortUTF.info
          fail_ci_if_error: true
          verbose: true