name: FortUTF Ubuntu Intel 2023

on: [push, pull_request]

jobs:
  build:
    name: Intel Latest Tests
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: actions/checkout@v4
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.31.x'
      - name: Setup Intel ifort compiler
        uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: intel
          version: '2023.2'
      - name: Build Tests
        run: |
            ifort --version
            cmake -H. -Bbuild -DBUILD_TESTS=ON -DCMAKE_Fortran_COMPILER=ifort
            cmake --build build
      - name: Run Tests
        run: |
             ./build/FortUTF_Tests
             if [ $? -eq 0 ]; then
                echo "Unit Tests completed successfully"
                exit 0
             else
                echo "Unit Tests failed"
                exit 1
             fi
      - name: Run Test List
        run: |
             ./build/FortUTF_Tests TEST_FAIL_EQUAL_CHAR TEST_EQUAL_CHAR
             if [ $? -eq 0 ]; then
                echo "Unit Tests completed succesfully"
                exit 0
             else
                echo "Unit Tests failed"
                exit 1
             fi
