name: FortUTF Windows GFortran 10

on: [push]

jobs:
  build:
    name: 'Windows Latest'
    runs-on: 'windows-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Install GFortran Windows
        uses: msys2/setup-msys2@v2
        with:
            update: true
            install: >-
                cmake
                gcc-fortran
                make
      - name: Build Tests
        shell: msys2 {0}
        run: |
            cmake -H. -Bbuild -DBUILD_TESTS=ON
            cmake --build build
      - name: Run Tests
        shell: msys2 {0}
        run: |
             ./build/FortUTF_Tests
             if [ $? -eq 0 ]; then
                echo "Unit Tests completed succesfully"
                exit 0
             else
                echo "Unit Tests failed"
                exit 1
             fi
