name: FUTS Linux

on: [push]

jobs:
  build: 
    name: Ubuntu Latest Tests
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Build Tests
        run: |
            cmake -H. -Bbuild -DBUILD_TESTS=ON
            cmake --build build
      - name: Run Tests
        run: ./build/FUTS_Tests

  build_example:
    name: Ubuntu Latest Example
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Build Example Project
        run: |
            cd examples/demo_project
            cmake -H. -Bbuild
            cmake --build build
            ./build/DEMO_PROJ_Tests

