name: FortUTF Windows GFortran 12

on: [push]

jobs:
  build:
    name: 'Windows Latest'
    runs-on: 'windows-latest'
    steps:
      - uses: actions/checkout@v3
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: '3.27.x'
      - name: Build and Run Tests
        run: |
            choco upgrade mingw --version="'12.2.0'" -y
            choco install -y make
            cmake -G "Unix Makefiles" -Bbuild -DBUILD_TESTS=ON
            cmake --build build
            ./build/FortUTF_Tests.exe

