name: FortUTF macOS GFortran 12

on: [push]

jobs:
  build:
    name: 'macOS Latest'
    runs-on: 'macos-latest'

    steps:
      - uses: actions/checkout@v2
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: '3.24.x'
      - name: Install GFortran macOS
        run: brew install gcc@12
      - name: Build Tests
        run: |
            cmake -H. -Bbuild -DBUILD_TESTS=ON -DCMAKE_Fortran_COMPILER=$(which gfortran-12)
            cmake --build build
      - name: Run Tests
        run: |
             ./build/FortUTF_Tests
             if [ $? -eq 0 ]; then
                echo "Unit Tests completed succesfully"
                exit 0
             else
                echo "Unit Tests failed"
                exit 1
             fi
