name: FortUTF macOS

on: [push]

jobs:
  build: 
    name: 'macOS Latest'
    runs-on: 'macos-latest'
    
    steps:
      - uses: actions/checkout@v2
      - name: Install GFortran macOS
        run: brew install gfortran
      - name: Build Tests
        run: |
            cmake -H. -Bbuild -DBUILD_TESTS=ON
            cmake --build build
      - name: Run Tests
        run: |
             ./build/FortUTF_Tests
             if [ $? -ne 0 ]; then
                echo "Unit Tests completed succesfully"
                exit 0
             else
                echo "Unit Tests failed"
                exit 1
             fi
