name: FUTS Linux

on: [push]

jobs:
  build: 
    name: Ubuntu Latest Tests
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Build Tests
        run: |
            cmake -H. -Bbuild -DBUILD_TESTS=ON
            cmake --build build
      - name: Run Tests
        run: |
            for i in $(ls build/bin/*); do ./$i; done
  build_example:
    name: Ubuntu Latest Example
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Build Example Project
        run: |
            cmake -H. -Bbuild -DBUILD_EXAMPLES=ON
            cmake --build build
      - name: Run Demo Project Tests
        run: ./build/bin/DEMO_PROJ

