name: FUTS macOS

on: [push]

jobs:
  build: 
    name: 'macOS Latest'
    runs-on: 'macos-latest'
    
    steps:
      - uses: actions/checkout@v2
      - name: Install GFortran macOS
        run: brew install gfortran
      - name: Build Tests
        run: |
            cmake -Htests -Bbuild
            cmake --build build
      - name: Run Tests
        run: |
            for i in $(ls build/bin/*); do ./$i; done
