name: FUTS Linux

on: [push]

jobs:
  build: 
    name: Ubuntu Latest
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Build Tests
        run: |
            cmake -Htests -Bbuild
            cmake --build build
      - name: Run Tests
        run: |
            for i in $(ls build/bin/*); do ./$i; done
  build_example:
    name: Run Examples
      - uses: actions/checkout@v2
      - name: Build Example Project
        run: |
            cmake -Hexamples/demo_project -Bbuild
            cmake --build build
      - name: Run Demo Project Tests
        run: ./build/bin/FUTS_Demo_Project_Tests

