name: FortUTF Ubuntu GFortran 10

on: [push]

jobs:
  build: 
    name: Ubuntu Latest Tests
    runs-on: 'ubuntu-20.04'
    steps:
      - uses: actions/checkout@v2
      - name: Build Tests
        run: |
            gfortran-10 --version
            cmake -H. -Bbuild -DBUILD_TESTS=ON -DCMAKE_Fortran_COMPILER=$(which gfortran-10)
            cmake --build build
      - name: Run Tests
        run: |
             ./build/FortUTF_Tests
             if [ $? -eq 0 ]; then
                echo "Unit Tests completed successfully"
                exit 0
             else
                echo "Unit Tests failed"
                exit 1
             fi
      - name: Get Coverage Data
        run: |
            sudo apt install -y lcov
            lcov --gcov-tool $(which gcov) --directory . --capture --output-file temp.info -b src/
            lcov --remove temp.info 'tests/*' 'tests/test_assertions/*' -o FortUTF.info
      - uses: codecov/codecov-action@v1
        with:
          file: FortUTF.info
          fail_ci_if_error: true
          verbose: true

