name: FortUTF Windows GFortran 10

on: [push]

jobs:
  build:
    name: 'Windows Latest'
    runs-on: 'windows-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: '3.20.x'
      - name: Build Tests
        run: |
            choco upgrade mingw --version="'10.2.0'" -y
            cmake -G "MinGW Makefiles" -Bbuild -DBUILD_TESTS=ON
            cmake --build build
      - name: Run Tests
        run: |
             ./build/FortUTF_Tests
             if [ $? -eq 0 ]; then
                echo "Unit Tests completed succesfully"
                exit 0
             else
                echo "Unit Tests failed"
                exit 1
             fi
